CREATE USER IF NOT EXISTS 'BUYDB_ADMIN'@'localhost' IDENTIFIED BY 'Lmxy20#a';
GRANT Alter ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Create ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Create view ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Delete ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Drop ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Grant option ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Index ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Insert ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT References ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Select ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Show view ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Trigger ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Update ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Alter routine ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Create routine ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Create temporary tables ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Execute ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Lock tables ON buypy.* TO 'BUYDB_ADMIN'@'localhost';
GRANT Grant option ON buypy.* TO 'BUYDB_ADMIN'@'localhost';

CREATE USER IF NOT EXISTS 'BUYDB_OPERATOR'@'localhost' IDENTIFIED BY 'Lmxy20#a';
GRANT Delete ON buypy.* TO 'BUYDB_OPERATOR'@'localhost';
GRANT Insert ON buypy.* TO 'BUYDB_OPERATOR'@'localhost';
GRANT Select ON buypy.* TO 'BUYDB_OPERATOR'@'localhost';
GRANT Update ON buypy.* TO 'BUYDB_OPERATOR'@'localhost';
GRANT Execute ON buypy.* TO 'BUYDB_OPERATOR'@'localhost';

CREATE USER IF NOT EXISTS 'WEB_CLIENT'@'localhost' IDENTIFIED BY 'Lmxy20#a';
GRANT Delete ON buypy.order TO 'WEB_CLIENT'@'localhost';
GRANT Delete ON buypy.ordered_item TO 'WEB_CLIENT'@'localhost';
GRANT Insert ON buypy.client TO 'WEB_CLIENT'@'localhost';
GRANT Insert ON buypy.order TO 'WEB_CLIENT'@'localhost';
GRANT Insert ON buypy.ordered_item TO 'WEB_CLIENT'@'localhost';
GRANT Select ON buypy.* TO 'WEB_CLIENT'@'localhost';
GRANT Update ON buypy.client TO 'WEB_CLIENT'@'localhost';
GRANT Update ON buypy.order TO 'WEB_CLIENT'@'localhost';
GRANT Update ON buypy.ordered_item TO 'WEB_CLIENT'@'localhost';
GRANT Update ( `quantity` ) ON buypy.product TO 'WEB_CLIENT'@'localhost';
GRANT Execute ON PROCEDURE buypy.AddProductToOrder TO 'WEB_CLIENT'@'localhost';
GRANT Execute ON PROCEDURE buypy.CreateOrder TO 'WEB_CLIENT'@'localhost';
GRANT Execute ON PROCEDURE buypy.GetOrderTotal TO 'WEB_CLIENT'@'localhost';
